name: snap_share_t3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_cli: ^1.8.4
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_database: ^10.3.6
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  http: ^0.13.6
  flutter_launcher_icons: ^0.13.1

 #icon generate command: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path_android: "assets/logos/android_logo.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logos/ios_logo.png"
  web:
    generate: false
  macos:
    generate: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf

